apiVersion: v1
kind: Service
metadata:
  name: toplista-api
  labels:
    app.kubernetes.io/name: toplista-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http # A kontener definicio portjara hivatkozik
      name: http # A service-en ezen neven lesz elerheto a port
  selector:
    app.kubernetes.io/name: toplista-api
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: toplista-api
  labels:
    app.kubernetes.io/name: toplista-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: toplista-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: toplista-api
    spec:
      containers:
        - name: toplista-api
          image: gameapp/toplista-api:v1
          ports:
            - name: http
              containerPort: 80
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: toplista-api
spec:
  rules:
  - http:
      paths:
      - path: /toplist
        backend:
          serviceName: toplista-api
          servicePort: 80
